#!/bin/bash -e

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Must be run as root. Try sudo companion-update"
    exit 1
fi

# stop companion
systemctl stop companion

# fetch new code
cd /usr/local/src/companion
git pull

# TODO - prompt for which branch to use

# do the update
./tools/companionpi/update.sh

# restart companion
# reboot
systemctl start companion